
name: PUSH Workflow

on:
  push:
    branches:
      - main 
  
  schedule:
    - cron: '30 6 * * 5' # every Monday 08:00 UTC 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2  
    
    - name: Configurar ambiente .NET
      uses: actions/setup-dotnet@v1 

    - name: Compilar projeto
      run: dotnet build --configuration Release

    - name: Executar testes
      run: dotnet test --no-restore --verbosity normal

    - name: Executar script personalizado
      run: |
        echo "Este é um script personalizado."
        echo "Pode executar comandos adicionais aqui."

    - name: Publicar artefatos
      if: success() 
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact 