name: PUSH-Validation

on: 
  push:

jobs:
  lint:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: On Schedule

on:
  schedule:
    - cron: `30 6 * * 5` # every Monday 08:00 UTC

jobs: 
  lint:
    name: Code Base

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
