
name: PUSH Workflow

on:
  push:
    branches:
      - main 
  
  schedule:
    - cron: '30 6 * * 5' # every Monday 08:00 UTC 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2.4.0  
    
    - name: Configurar ambiente .NET
      uses: actions/setup-dotnet@v1

    - name: Executar script personalizado
      run: |
        echo "Este é um script personalizado."
        echo "Pode executar comandos adicionais aqui."

    - name: Publicar artefatos
      if: success() 
      uses: actions/upload-artifact@v2.2.4
      with:
        name: my-artifact
        path: .