
name: PUSH Workflow

on:
  push:
    branches:
      - main 
  
  schedule:
    - cron: '30 6 * * 5' # every Monday 08:00 UTC 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
    
    - name: Lint Code Base
      uses: github/super-linter@v3

    - name: Executar script personalizado
      run: |
        echo "Este é um script personalizado."
        echo "Pode executar comandos adicionais aqui."

    